config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'examples#index'

  resources :examples, only: :index do
    get :buttons, :cards, :utilities_color, :utilities_border,
        :utilities_animation, :utilities_other, :login, :register,
        :forgot_password, :page_404, :blank, :charts, :tables,
        on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_variables
  layout 'auth', only: %i[login register forgot_password]

  private

  def set_variables
    @notifications = [
      OpenStruct.new(date: 'December 12, 2019', content: 'A new monthly report is ready to download!', kind: 'primary', viewed: false),
      OpenStruct.new(date: 'December 7, 2019', content: '$290.29 has been deposited into your account!', kind: 'success', viewed: true),
      OpenStruct.new(date: 'December 2, 2019', content: 'Spending Alert: We\'ve noticed unusually high spending for your account.', kind: 'warning', viewed: true)
    ]

    @messages = [
      OpenStruct.new(content: "Hi there! I am wondering if you can help me with a problem I've been having.", sender: "Emily Fowler · 58m", sender_avatar: 'https://source.unsplash.com/fn_BT9fwg_E/60x60'),
      OpenStruct.new(content: "I have the photos that you ordered last month, how would you like them sent to you?", sender: "Jae Chun · 1d", sender_avatar: 'https://source.unsplash.com/AU4VPcFN4LE/60x60'),
      OpenStruct.new(content: "Last month's report looks great, I am very happy with the progress so far, keep up the good work!", sender: "Morgan Alvarez · 2d", sender_avatar: 'https://source.unsplash.com/CS2uCrpNzJY/60x60'),
      OpenStruct.new(content: "Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...", sender: "Chicken the Dog · 2w", sender_avatar: 'https://source.unsplash.com/Mv9hjnEUHR4/60x60')
    ]
  end
end

app/helpers/active_link_to_helper.rb
module ActiveLinkToHelper
  def active_link_to(*args)
    if block_given?
      link_to args[0], *options_with_active_class(args, true) do
        yield
      end
    else
      link_to args[0], args[1], *options_with_active_class(args, false)
    end
  end

  def add_active_class(option)
    return 'active' if active_link?(option)
  end

  def active_link?(option)
    return current_page?(option) if option.is_a? String

    return nil unless option.is_a? Hash

    return current_page?(option[:path]) if option[:path]

    if option[:starting_with]
      return request.path.start_with? option[:starting_with]
    end

    if option[:includes]
      includes = [option[:includes]].flatten
      return includes.any? { |elem| request.path.include? elem }
    end
  end

  private

  def options_with_active_class(args, block)
    path = block ? args[0] : args[1]
    options_array = block ? args[1..-1] : args[2..-1]
    options = {}.merge(*options_array).symbolize_keys

    return options_array unless active_link?(options.merge({ path: path }))

    if options[:class].is_a? String
      options[:class] += ' active'
    else
      'active'
    end

    options.map {|k,v| {k => v}}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActiveLinkToHelper
  include TemplateNavHelper
end

app/helpers/template_nav_helper.rb
module TemplateNavHelper
  def nav_context(name, title, icon: '', active_link: false, &block)
    "<li class='nav-item #{'active' if active_link}'>
      <a class='nav-link #{'collapsed' unless active_link}'
        href='#' data-toggle='collapse' 
        data-target='##{name}'
        aria-expanded='true'
        aria-controls='#{name}'>
        <i class='fas fa-fw fa-#{icon}'></i>
        <span>#{title}</span>
      </a>
      <div id='#{name}'
        class='collapse #{'show' if active_link}'
        aria-labelledby='headingTwo'
        data-parent='#accordionSidebar'>
        <div class='bg-white py-2 collapse-inner rounded'>
          #{capture(&block)}
        </div>
      </div>
    </li>".html_safe
  end
end

app/views/examples/blank.html.erb
<h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

app/views/examples/buttons.html.erb
<h1 class="h3 mb-4 text-gray-800">Buttons</h1>

<div class="row">

  <div class="col-lg-6">

    <!-- Circle Buttons -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Circle Buttons</h6>
      </div>
      <div class="card-body">
        <p>Use Font Awesome Icons (included with this theme package) along with the circle buttons as shown in the examples below!</p>
        <!-- Circle Buttons (Default) -->
        <div class="mb-2">
          <code>.btn-circle</code>
        </div>
        <a href="#" class="btn btn-primary btn-circle">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#" class="btn btn-success btn-circle">
          <i class="fas fa-check"></i>
        </a>
        <a href="#" class="btn btn-info btn-circle">
          <i class="fas fa-info-circle"></i>
        </a>
        <a href="#" class="btn btn-warning btn-circle">
          <i class="fas fa-exclamation-triangle"></i>
        </a>
        <a href="#" class="btn btn-danger btn-circle">
          <i class="fas fa-trash"></i>
        </a>
        <!-- Circle Buttons (Small) -->
        <div class="mt-4 mb-2">
          <code>.btn-circle .btn-sm</code>
        </div>
        <a href="#" class="btn btn-primary btn-circle btn-sm">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#" class="btn btn-success btn-circle btn-sm">
          <i class="fas fa-check"></i>
        </a>
        <a href="#" class="btn btn-info btn-circle btn-sm">
          <i class="fas fa-info-circle"></i>
        </a>
        <a href="#" class="btn btn-warning btn-circle btn-sm">
          <i class="fas fa-exclamation-triangle"></i>
        </a>
        <a href="#" class="btn btn-danger btn-circle btn-sm">
          <i class="fas fa-trash"></i>
        </a>
        <!-- Circle Buttons (Large) -->
        <div class="mt-4 mb-2">
          <code>.btn-circle .btn-lg</code>
        </div>
        <a href="#" class="btn btn-primary btn-circle btn-lg">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#" class="btn btn-success btn-circle btn-lg">
          <i class="fas fa-check"></i>
        </a>
        <a href="#" class="btn btn-info btn-circle btn-lg">
          <i class="fas fa-info-circle"></i>
        </a>
        <a href="#" class="btn btn-warning btn-circle btn-lg">
          <i class="fas fa-exclamation-triangle"></i>
        </a>
        <a href="#" class="btn btn-danger btn-circle btn-lg">
          <i class="fas fa-trash"></i>
        </a>
      </div>
    </div>

    <!-- Brand Buttons -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Brand Buttons</h6>
      </div>
      <div class="card-body">
        <p>Google and Facebook buttons are available featuring each company's respective brand color. They are used on the user login and registration pages.</p>
        <p>You can create more custom buttons by adding a new color variable in the <code>_variables.scss</code> file and then using the Bootstrap button variant mixin to create a new style, as demonstrated in the <code>_buttons.scss</code> file.</p>
        <a href="#" class="btn btn-google btn-block"><i class="fab fa-google fa-fw"></i> .btn-google</a>
        <a href="#" class="btn btn-facebook btn-block"><i class="fab fa-facebook-f fa-fw"></i> .btn-facebook</a>

      </div>
    </div>

  </div>

  <div class="col-lg-6">

    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Split Buttons with Icon</h6>
      </div>
      <div class="card-body">
        <p>Works with any button colors, just use the <code>.btn-icon-split</code> class and the markup in the examples below. The examples below also use the <code>.text-white-50</code> helper class on the icons for additional styling, but it is not required.</p>
        <a href="#" class="btn btn-primary btn-icon-split">
          <span class="icon text-white-50">
            <i class="fas fa-flag"></i>
          </span>
          <span class="text">Split Button Primary</span>
        </a>
        <div class="my-2"></div>
        <a href="#" class="btn btn-success btn-icon-split">
          <span class="icon text-white-50">
            <i class="fas fa-check"></i>
          </span>
          <span class="text">Split Button Success</span>
        </a>
        <div class="my-2"></div>
        <a href="#" class="btn btn-info btn-icon-split">
          <span class="icon text-white-50">
            <i class="fas fa-info-circle"></i>
          </span>
          <span class="text">Split Button Info</span>
        </a>
        <div class="my-2"></div>
        <a href="#" class="btn btn-warning btn-icon-split">
          <span class="icon text-white-50">
            <i class="fas fa-exclamation-triangle"></i>
          </span>
          <span class="text">Split Button Warning</span>
        </a>
        <div class="my-2"></div>
        <a href="#" class="btn btn-danger btn-icon-split">
          <span class="icon text-white-50">
            <i class="fas fa-trash"></i>
          </span>
          <span class="text">Split Button Danger</span>
        </a>
        <div class="my-2"></div>
        <a href="#" class="btn btn-secondary btn-icon-split">
          <span class="icon text-white-50">
            <i class="fas fa-arrow-right"></i>
          </span>
          <span class="text">Split Button Secondary</span>
        </a>
        <div class="my-2"></div>
        <a href="#" class="btn btn-light btn-icon-split">
          <span class="icon text-gray-600">
            <i class="fas fa-arrow-right"></i>
          </span>
          <span class="text">Split Button Primary</span>
        </a>
        <div class="mb-4"></div>
        <p>Also works with small and large button classes!</p>
        <a href="#" class="btn btn-primary btn-icon-split btn-sm">
          <span class="icon text-white-50">
            <i class="fas fa-flag"></i>
          </span>
          <span class="text">Split Button Small</span>
        </a>
        <div class="my-2"></div>
        <a href="#" class="btn btn-primary btn-icon-split btn-lg">
          <span class="icon text-white-50">
            <i class="fas fa-flag"></i>
          </span>
          <span class="text">Split Button Large</span>
        </a>
      </div>
    </div>

  </div>

</div>

app/views/examples/cards.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Cards</h1>
</div>

<div class="row">

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Earnings (Monthly)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-success shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Earnings (Annual)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks</div>
            <div class="row no-gutters align-items-center">
              <div class="col-auto">
                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
              </div>
              <div class="col">
                <div class="progress progress-sm mr-2">
                  <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-auto">
            <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Pending Requests Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending Requests</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-comments fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">

  <div class="col-lg-6">

    <!-- Default Card Example -->
    <div class="card mb-4">
      <div class="card-header">
        Default Card Example
      </div>
      <div class="card-body">
        This card uses Bootstrap's default styling with no utility classes added. Global styles are the only things modifying the look and feel of this default card example.
      </div>
    </div>

    <!-- Basic Card Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Basic Card Example</h6>
      </div>
      <div class="card-body">
        The styling for this basic card example is created by using default Bootstrap utility classes. By using utility classes, the style of the card component can be easily modified with no need for any custom CSS!
      </div>
    </div>

  </div>

  <div class="col-lg-6">

    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Dropdown Card Example</h6>
        <div class="dropdown no-arrow">
          <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
            <div class="dropdown-header">Dropdown Header:</div>
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </div>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        Dropdown menus can be placed in the card header in order to extend the functionality of a basic card. In this dropdown card example, the Font Awesome vertical ellipsis icon in the card header can be clicked on in order to toggle a dropdown menu.
      </div>
    </div>

    <!-- Collapsable Card Example -->
    <div class="card shadow mb-4">
      <!-- Card Header - Accordion -->
      <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
        <h6 class="m-0 font-weight-bold text-primary">Collapsable Card Example</h6>
      </a>
      <!-- Card Content - Collapse -->
      <div class="collapse show" id="collapseCardExample">
        <div class="card-body">
          This is a collapsable card example using Bootstrap's built in collapse functionality. <strong>Click on the card header</strong> to see the card body collapse and expand!
        </div>
      </div>
    </div>

  </div>

</div>

app/views/examples/charts.html.erb
<h1 class="h3 mb-2 text-gray-800">Charts</h1>
<p class="mb-4">Chart.js is a third party plugin that is used to generate the charts in this theme. The charts below have been customized - for further customization options, please visit the <a target="_blank" href="https://www.chartjs.org/docs/latest/">official Chart.js documentation</a>.</p>

<!-- Content Row -->
<div class="row">

  <div class="col-xl-8 col-lg-7">

    <!-- Area Chart -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
      </div>
      <div class="card-body">
        <div class="chart-area">
          <canvas id="myAreaChart"></canvas>
        </div>
        <hr>
        Styling for the area chart can be found in the <code>/js/demo/chart-area-demo.js</code> file.
      </div>
    </div>

    <!-- Bar Chart -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
      </div>
      <div class="card-body">
        <div class="chart-bar">
          <canvas id="myBarChart"></canvas>
        </div>
        <hr>
        Styling for the bar chart can be found in the <code>/js/demo/chart-bar-demo.js</code> file.
      </div>
    </div>

  </div>

  <!-- Donut Chart -->
  <div class="col-xl-4 col-lg-5">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <div class="chart-pie pt-4">
          <canvas id="myPieChart"></canvas>
        </div>
        <hr>
        Styling for the donut chart can be found in the <code>/js/demo/chart-pie-demo.js</code> file.
      </div>
    </div>
  </div>
</div>

app/views/examples/forgot_password.html.erb
<div class="row">
  <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
  <div class="col-lg-6">
    <div class="p-5">
      <div class="text-center">
        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
        <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
      </div>
      <form class="user">
        <div class="form-group">
          <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
        </div>
        <a href="<%= login_examples_path %>" class="btn btn-primary btn-user btn-block">
          Reset Password
        </a>
      </form>
      <hr>
      <div class="text-center">
        <a class="small" href="<%= register_examples_path %>">Create an Account!</a>
      </div>
      <div class="text-center">
        <a class="small" href="<%= login_examples_path %>">Already have an account? Login!</a>
      </div>
    </div>
  </div>
</div>

app/views/examples/login.html.erb
<div class="row">
  <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
  <div class="col-lg-6">
    <div class="p-5">
      <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
      </div>
      <form class="user">
        <div class="form-group">
          <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
        </div>
        <div class="form-group">
          <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
        </div>
        <div class="form-group">
          <div class="custom-control custom-checkbox small">
            <input type="checkbox" class="custom-control-input" id="customCheck">
            <label class="custom-control-label" for="customCheck">Remember Me</label>
          </div>
        </div>
        <a href="<%= examples_path %>" class="btn btn-primary btn-user btn-block">
          Login
        </a>
        <hr>
        <a href="<%= examples_path %>" class="btn btn-google btn-user btn-block">
          <i class="fab fa-google fa-fw"></i> Login with Google
        </a>
        <a href="<%= examples_path %>" class="btn btn-facebook btn-user btn-block">
          <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
        </a>
      </form>
      <hr>
      <div class="text-center">
        <a class="small" href="<%= forgot_password_examples_path %>">Forgot Password?</a>
      </div>
      <div class="text-center">
        <a class="small" href="<%= register_examples_path %>">Create an Account!</a>
      </div>
    </div>
  </div>
</div>

app/views/examples/page_404.html.erb
<!-- 404 Error Text -->
<div class="text-center">
  <div class="error mx-auto" data-text="404">404</div>
  <p class="lead text-gray-800 mb-5">Page Not Found</p>
  <p class="text-gray-500 mb-0">It looks like you found a glitch in the matrix...</p>
  <a href="<%= examples_path %>">&larr; Back to Dashboard</a>
</div>

app/views/examples/register.html.erb
<div class="row">
  <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
  <div class="col-lg-7">
    <div class="p-5">
      <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
      </div>
      <form class="user">
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">
          </div>
          <div class="col-sm-6">
            <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">
          </div>
        </div>
        <div class="form-group">
          <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
        </div>
        <div class="form-group row">
          <div class="col-sm-6 mb-3 mb-sm-0">
            <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
          </div>
          <div class="col-sm-6">
            <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
          </div>
        </div>
        <a href="<%= login_examples_path %>" class="btn btn-primary btn-user btn-block">
          Register Account
        </a>
        <hr>
        <a href="<%= examples_path %>" class="btn btn-google btn-user btn-block">
          <i class="fab fa-google fa-fw"></i> Register with Google
        </a>
        <a href="<%= examples_path %>" class="btn btn-facebook btn-user btn-block">
          <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
        </a>
      </form>
      <hr>
      <div class="text-center">
        <a class="small" href="<%= forgot_password_examples_path %>">Forgot Password?</a>
      </div>
      <div class="text-center">
        <a class="small" href="<%= login_examples_path %>">Already have an account? Login!</a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Template</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="page-top">

    <div id="wrapper">
      <%= render  "layouts/shared/sidebar" %>

      <div id="content-wrapper" class="d-flex flex-column">

        <div id="content">
          <%= render "layouts/shared/topbar" %>

          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>

        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Your Website 2019</span>
            </div>
          </div>
        </footer>

      </div>

    </div>

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <%= render "layouts/shared/logout_modal" %>
  </body>
</html>

app/views/layouts/shared/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item">
    <a class="nav-link" href="<%= root_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Interface
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <% active_context = active_link?(includes: ['buttons', 'cards']) %>

  <%= nav_context :components, 'Components', icon: 'cog', active_link: active_context do %>
    <h6 class="collapse-header">Custom Components:</h6>
    <%= active_link_to 'Buttons', buttons_examples_path, class: 'collapse-item' %>
    <%= active_link_to 'Cards', cards_examples_path, class: 'collapse-item' %>
  <% end %>

  <!-- Nav Item - Utilities Collapse Menu -->
  <%= nav_context :utilities, 'Utilities', icon: 'wrench' do %>
    <h6 class="collapse-header">Custom Utilities:</h6>
    <%= active_link_to 'Colors', utilities_color_examples_path, class: 'collapse-item' %>
    <%= active_link_to 'Borders', utilities_border_examples_path, class: 'collapse-item' %>
    <%= active_link_to 'Animations', utilities_animation_examples_path, class: 'collapse-item' %>
    <%= active_link_to 'Other', utilities_other_examples_path, class: 'collapse-item' %>
  <% end %>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Addons
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <%= nav_context :pages, 'Pages', icon: 'folder' do %>
    <h6 class="collapse-header">Login Screens:</h6>
    <%= active_link_to "Login", login_examples_path, class: 'collapse-item' %>
    <%= active_link_to "Register", register_examples_path, class: 'collapse-item' %>
    <%= active_link_to "Forgot Password", forgot_password_examples_path, class: 'collapse-item' %>
    <div class="collapse-divider"></div>
    <h6 class="collapse-header">Other Pages:</h6>
    <%= active_link_to "404 Page", page_404_examples_path, class: 'collapse-item' %>
    <%= active_link_to "Blank Page", blank_examples_path, class: 'collapse-item' %>
  <% end %>

  <!-- Nav Item - Charts -->
  <li class="nav-item <%= add_active_class(charts_examples_path) %>">
    <a class="nav-link" href="<%= charts_examples_path %>">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Charts</span>
    </a>
  </li>

  <!-- Nav Item - Tables -->
  <li class="nav-item <%= add_active_class(tables_examples_path) %>">
    <a class="nav-link" href="<%= tables_examples_path %>">
      <i class="fas fa-fw fa-table"></i>
      <span>Tables</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
<!-- End of Sidebar -->